name = "reliatools"
pages_build_output_dir = ".vercel/output/static"

# Node‑style APIs (fs, path, Buffer, etc.) for @cloudflare/next‑on‑pages
compatibility_flags = ["nodejs_compat_populate_process_env"]
