name = "reliatools"
pages_build_output_dir = ".vercel/output/static"

# ✨ ADD THIS LINE – pick today’s date (YYYY‑MM‑DD)
compatibility_date = "2025-05-04"

# Node‑style APIs (fs, path, Buffer, etc.) for @cloudflare/next‑on‑pages
compatibility_flags = ["nodejs_compat_populate_process_env"]
