import type { MissionTemplatePreset } from "./schema";

const BASE_DEFAULTS: MissionTemplatePreset["defaults"] = {
  temperature_extremes: { minC: -10, maxC: 60, dwellMin: 60 },
  thermal_cycles: { deltaC: 40, cyclesPerDay: 1, rampRateCMin: 1.5 },
  humidity: { rhPct: 70, condensingHoursWeek: 4 },
  vibration: { grms: 2, freqMinHz: 10, freqMaxHz: 500 },
  mechanical_shock: { gPeak: 20, pulseMs: 11, eventsPerMonth: 5 },
  esd: { contactKv: 4, airKv: 8 },
  salt_fog: { naclPct: 5, hoursPerWeek: 8 },
  chemical_exposure: { severityIndex: 3, hoursPerWeek: 2 },
  dust_ingress: { pmMgM3: 50, hoursPerWeek: 8 },
};

export const MISSION_PROFILE_TEMPLATES: MissionTemplatePreset[] = [
  {
    id: "auto-ecu-engine-bay",
    industry: "Automotive",
    product: "ECU",
    location: "Engine bay",
    description: "High heat and cycling near engine with moderate vibration.",
    defaults: {
      ...BASE_DEFAULTS,
      temperature_extremes: { minC: -40, maxC: 125, dwellMin: 45 },
      thermal_cycles: { deltaC: 90, cyclesPerDay: 3, rampRateCMin: 2.5 },
      humidity: { rhPct: 85, condensingHoursWeek: 10 },
      vibration: { grms: 5, freqMinHz: 10, freqMaxHz: 1500 },
      chemical_exposure: { severityIndex: 6, hoursPerWeek: 4 },
    },
    likelihoods: {
      temperature_extremes: { transport: "possible", operation: "likely", maintenance: "likely" },
      thermal_cycles: { operation: "likely", maintenance: "likely", abuse: "possible" },
      humidity: { transport: "possible", operation: "possible", maintenance: "possible" },
      vibration: { transport: "possible", operation: "likely", abuse: "likely" },
      mechanical_shock: { transport: "possible", assembly: "possible", abuse: "likely" },
      esd: { assembly: "possible", maintenance: "possible" },
      salt_fog: { transport: "possible", operation: "possible" },
      chemical_exposure: { operation: "possible", maintenance: "likely" },
      dust_ingress: { operation: "possible", maintenance: "possible" },
    },
  },
  {
    id: "auto-ecu-cabin",
    industry: "Automotive",
    product: "ECU",
    location: "Cabin",
    description: "Moderate thermal/vibration loading for interior electronics.",
    defaults: {
      ...BASE_DEFAULTS,
      temperature_extremes: { minC: -20, maxC: 85, dwellMin: 60 },
      thermal_cycles: { deltaC: 45, cyclesPerDay: 2, rampRateCMin: 1.5 },
      humidity: { rhPct: 75, condensingHoursWeek: 5 },
      vibration: { grms: 2.5, freqMinHz: 10, freqMaxHz: 1000 },
      esd: { contactKv: 6, airKv: 12 },
    },
    likelihoods: {
      temperature_extremes: { transport: "possible", operation: "possible", maintenance: "possible" },
      thermal_cycles: { operation: "possible" },
      humidity: { operation: "possible", maintenance: "possible" },
      vibration: { transport: "possible", operation: "possible", abuse: "possible" },
      mechanical_shock: { transport: "possible", abuse: "possible" },
      esd: { assembly: "likely", operation: "possible", maintenance: "likely", abuse: "possible" },
      salt_fog: { transport: "possible" },
      chemical_exposure: { maintenance: "possible" },
      dust_ingress: { operation: "possible" },
    },
  },
  {
    id: "auto-ecu-underbody",
    industry: "Automotive",
    product: "ECU",
    location: "Underbody",
    description: "Road splash, debris, and vibration dominate duty cycle.",
    defaults: {
      ...BASE_DEFAULTS,
      temperature_extremes: { minC: -40, maxC: 95, dwellMin: 60 },
      thermal_cycles: { deltaC: 60, cyclesPerDay: 2, rampRateCMin: 1.8 },
      humidity: { rhPct: 90, condensingHoursWeek: 20 },
      vibration: { grms: 6, freqMinHz: 8, freqMaxHz: 2000 },
      mechanical_shock: { gPeak: 35, pulseMs: 8, eventsPerMonth: 20 },
      salt_fog: { naclPct: 5, hoursPerWeek: 16 },
      dust_ingress: { pmMgM3: 200, hoursPerWeek: 20 },
    },
    likelihoods: {
      temperature_extremes: { transport: "possible", operation: "likely", maintenance: "possible" },
      thermal_cycles: { operation: "likely", abuse: "possible" },
      humidity: { transport: "possible", operation: "likely", maintenance: "likely" },
      vibration: { transport: "possible", operation: "likely", abuse: "likely" },
      mechanical_shock: { transport: "possible", operation: "possible", abuse: "likely" },
      esd: { assembly: "possible", maintenance: "possible" },
      salt_fog: { transport: "possible", operation: "likely", maintenance: "possible" },
      chemical_exposure: { operation: "possible", maintenance: "possible" },
      dust_ingress: { operation: "likely", maintenance: "possible" },
    },
  },
  {
    id: "consumer-laptop-indoor",
    industry: "Consumer",
    product: "Laptop",
    location: "Indoor office",
    description: "Portable use with moderate thermal cycles and handling shock.",
    defaults: {
      ...BASE_DEFAULTS,
      temperature_extremes: { minC: 5, maxC: 45, dwellMin: 30 },
      thermal_cycles: { deltaC: 25, cyclesPerDay: 4, rampRateCMin: 3 },
      humidity: { rhPct: 65, condensingHoursWeek: 1 },
      vibration: { grms: 1.2, freqMinHz: 10, freqMaxHz: 600 },
      mechanical_shock: { gPeak: 45, pulseMs: 4, eventsPerMonth: 8 },
      esd: { contactKv: 4, airKv: 10 },
    },
    likelihoods: {
      temperature_extremes: { transport: "possible", operation: "possible", abuse: "possible" },
      thermal_cycles: { operation: "likely" },
      humidity: { operation: "possible", maintenance: "possible" },
      vibration: { transport: "possible", operation: "possible" },
      mechanical_shock: { transport: "likely", operation: "possible", abuse: "likely" },
      esd: { assembly: "possible", operation: "possible", maintenance: "likely", abuse: "possible" },
      salt_fog: { transport: "possible" },
      chemical_exposure: { maintenance: "possible" },
      dust_ingress: { operation: "possible" },
    },
  },
  {
    id: "consumer-desktop-indoor",
    industry: "Consumer",
    product: "Desktop",
    location: "Indoor office",
    description: "Mostly steady indoor use with fan vibration and dust.",
    defaults: {
      ...BASE_DEFAULTS,
      temperature_extremes: { minC: 10, maxC: 40, dwellMin: 60 },
      thermal_cycles: { deltaC: 15, cyclesPerDay: 1, rampRateCMin: 1 },
      humidity: { rhPct: 60, condensingHoursWeek: 0.5 },
      vibration: { grms: 0.8, freqMinHz: 20, freqMaxHz: 1200 },
      dust_ingress: { pmMgM3: 80, hoursPerWeek: 20 },
    },
    likelihoods: {
      temperature_extremes: { transport: "possible", operation: "possible" },
      thermal_cycles: { operation: "possible" },
      humidity: { operation: "possible" },
      vibration: { transport: "possible", operation: "possible" },
      mechanical_shock: { transport: "possible", abuse: "possible" },
      esd: { assembly: "possible", maintenance: "possible" },
      salt_fog: { transport: "possible" },
      chemical_exposure: { maintenance: "possible" },
      dust_ingress: { operation: "likely", maintenance: "likely" },
    },
  },
  {
    id: "consumer-refrigerator-kitchen",
    industry: "Consumer",
    product: "Refrigerator",
    location: "Kitchen",
    description: "High humidity and compressor-induced cycling.",
    defaults: {
      ...BASE_DEFAULTS,
      temperature_extremes: { minC: -25, maxC: 55, dwellMin: 120 },
      thermal_cycles: { deltaC: 35, cyclesPerDay: 6, rampRateCMin: 1.2 },
      humidity: { rhPct: 90, condensingHoursWeek: 18 },
      vibration: { grms: 2.2, freqMinHz: 15, freqMaxHz: 400 },
      chemical_exposure: { severityIndex: 4, hoursPerWeek: 1 },
    },
    likelihoods: {
      temperature_extremes: { operation: "likely", maintenance: "possible" },
      thermal_cycles: { operation: "likely", maintenance: "possible" },
      humidity: { transport: "possible", operation: "likely", maintenance: "likely" },
      vibration: { transport: "possible", operation: "possible" },
      mechanical_shock: { transport: "possible", abuse: "possible" },
      esd: { assembly: "possible", maintenance: "possible" },
      salt_fog: { operation: "possible" },
      chemical_exposure: { operation: "possible", maintenance: "possible" },
      dust_ingress: { operation: "possible", maintenance: "possible" },
    },
  },
  {
    id: "industrial-control-cabinet-floor",
    industry: "Industrial",
    product: "Control cabinet",
    location: "Factory floor",
    description: "Steady operation with contamination and service exposure.",
    defaults: {
      ...BASE_DEFAULTS,
      temperature_extremes: { minC: 0, maxC: 65, dwellMin: 120 },
      thermal_cycles: { deltaC: 20, cyclesPerDay: 0.5, rampRateCMin: 0.8 },
      humidity: { rhPct: 75, condensingHoursWeek: 6 },
      vibration: { grms: 1.8, freqMinHz: 10, freqMaxHz: 800 },
      dust_ingress: { pmMgM3: 120, hoursPerWeek: 30 },
      chemical_exposure: { severityIndex: 5, hoursPerWeek: 4 },
    },
    likelihoods: {
      temperature_extremes: { operation: "possible", maintenance: "possible" },
      thermal_cycles: { operation: "possible" },
      humidity: { operation: "possible", maintenance: "possible" },
      vibration: { transport: "possible", operation: "possible" },
      mechanical_shock: { transport: "possible", maintenance: "possible", abuse: "possible" },
      esd: { assembly: "possible", maintenance: "likely" },
      salt_fog: { operation: "possible" },
      chemical_exposure: { operation: "possible", maintenance: "likely" },
      dust_ingress: { operation: "likely", maintenance: "likely" },
    },
  },
  {
    id: "industrial-outdoor-sensor-field",
    industry: "Industrial",
    product: "Outdoor sensor",
    location: "Field outdoor",
    description: "Outdoor weathering, condensation, and contamination profile.",
    defaults: {
      ...BASE_DEFAULTS,
      temperature_extremes: { minC: -40, maxC: 85, dwellMin: 180 },
      thermal_cycles: { deltaC: 50, cyclesPerDay: 1, rampRateCMin: 0.8 },
      humidity: { rhPct: 95, condensingHoursWeek: 25 },
      vibration: { grms: 1.5, freqMinHz: 5, freqMaxHz: 300 },
      mechanical_shock: { gPeak: 30, pulseMs: 10, eventsPerMonth: 3 },
      salt_fog: { naclPct: 5, hoursPerWeek: 12 },
      dust_ingress: { pmMgM3: 250, hoursPerWeek: 40 },
    },
    likelihoods: {
      temperature_extremes: { transport: "possible", operation: "likely", abuse: "possible" },
      thermal_cycles: { operation: "likely", maintenance: "possible" },
      humidity: { operation: "likely", maintenance: "likely" },
      vibration: { transport: "possible", operation: "possible" },
      mechanical_shock: { transport: "possible", operation: "possible", abuse: "possible" },
      esd: { maintenance: "possible" },
      salt_fog: { operation: "likely", maintenance: "possible" },
      chemical_exposure: { operation: "possible", maintenance: "possible" },
      dust_ingress: { operation: "likely", maintenance: "likely" },
    },
  },
  {
    id: "dc-server-node-rack",
    industry: "DataCenterAI",
    product: "Server node",
    location: "Rack aisle",
    description: "High uptime with fan vibration and mild thermal cycling.",
    defaults: {
      ...BASE_DEFAULTS,
      temperature_extremes: { minC: 10, maxC: 45, dwellMin: 120 },
      thermal_cycles: { deltaC: 20, cyclesPerDay: 1, rampRateCMin: 1 },
      humidity: { rhPct: 60, condensingHoursWeek: 0 },
      vibration: { grms: 1.4, freqMinHz: 30, freqMaxHz: 2000 },
      esd: { contactKv: 2, airKv: 4 },
    },
    likelihoods: {
      temperature_extremes: { transport: "possible", operation: "possible" },
      thermal_cycles: { operation: "possible" },
      humidity: { operation: "possible" },
      vibration: { transport: "possible", operation: "likely" },
      mechanical_shock: { transport: "possible", abuse: "possible" },
      esd: { assembly: "possible", maintenance: "possible" },
      salt_fog: { transport: "possible" },
      chemical_exposure: { maintenance: "possible" },
      dust_ingress: { operation: "possible", maintenance: "possible" },
    },
  },
  {
    id: "dc-psu-rack",
    industry: "DataCenterAI",
    product: "PSU",
    location: "Rack PSU bay",
    description: "Elevated local heat and replacement handling stress.",
    defaults: {
      ...BASE_DEFAULTS,
      temperature_extremes: { minC: 10, maxC: 60, dwellMin: 180 },
      thermal_cycles: { deltaC: 25, cyclesPerDay: 1.2, rampRateCMin: 1.5 },
      humidity: { rhPct: 60, condensingHoursWeek: 0 },
      vibration: { grms: 1.1, freqMinHz: 20, freqMaxHz: 1200 },
      mechanical_shock: { gPeak: 25, pulseMs: 8, eventsPerMonth: 2 },
    },
    likelihoods: {
      temperature_extremes: { transport: "possible", operation: "likely", maintenance: "possible" },
      thermal_cycles: { operation: "possible", maintenance: "possible" },
      humidity: { operation: "possible" },
      vibration: { transport: "possible", operation: "possible" },
      mechanical_shock: { transport: "likely", maintenance: "likely", abuse: "possible" },
      esd: { assembly: "possible", maintenance: "likely" },
      salt_fog: { transport: "possible" },
      chemical_exposure: { maintenance: "possible" },
      dust_ingress: { operation: "possible", maintenance: "possible" },
    },
  },
  {
    id: "dc-fan-module-chassis",
    industry: "DataCenterAI",
    product: "Fan module",
    location: "Server chassis",
    description: "Continuous high-speed vibration with periodic replacement events.",
    defaults: {
      ...BASE_DEFAULTS,
      temperature_extremes: { minC: 10, maxC: 55, dwellMin: 90 },
      thermal_cycles: { deltaC: 18, cyclesPerDay: 1, rampRateCMin: 1.2 },
      humidity: { rhPct: 55, condensingHoursWeek: 0 },
      vibration: { grms: 3.5, freqMinHz: 40, freqMaxHz: 2500 },
      mechanical_shock: { gPeak: 20, pulseMs: 6, eventsPerMonth: 1 },
      dust_ingress: { pmMgM3: 60, hoursPerWeek: 40 },
    },
    likelihoods: {
      temperature_extremes: { operation: "possible", maintenance: "possible" },
      thermal_cycles: { operation: "possible" },
      humidity: { operation: "possible" },
      vibration: { transport: "possible", operation: "likely", abuse: "possible" },
      mechanical_shock: { transport: "possible", maintenance: "likely", abuse: "possible" },
      esd: { assembly: "possible", maintenance: "possible" },
      salt_fog: { transport: "possible" },
      chemical_exposure: { maintenance: "possible" },
      dust_ingress: { operation: "likely", maintenance: "possible" },
    },
  },
];

export function getTemplateById(id: string): MissionTemplatePreset | undefined {
  return MISSION_PROFILE_TEMPLATES.find((template) => template.id === id);
}

export function getTemplatesForIndustry(industry: string): MissionTemplatePreset[] {
  return MISSION_PROFILE_TEMPLATES.filter((template) => template.industry === industry);
}
